pipeline:
  clone:
    image: plugins/git
    recursive: true
    depth: 10
    tags: true

  master-pr-build:
    image: library/java:8
    pull: true
    when:
      branch: master
      event: pull_request
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2400M
    commands:
      - mvn clean install

  master-push-build:
    image: library/java:8
    pull: true
    when:
      branch: master
      event: push
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2400M
    commands:
      - mvn clean install

  publish-docker-image-release:
    when:
      event: tag
      ref: refs/tags/v*
    image: plugins/docker:latest
    username: Siddarththiyagarajan
    password: Scarface@105
    registry: hub.docker.com
    repo: sid105/my_retail_repo
    tags: latest
