version: '3'
services:
  myretailapp:
    image: myretailapp
    build: .
    deploy:
        replicas: 5
    ports:
      - 8080:8080
    depends_on:
      - cassandra-load-keyspace
    networks:
      - myretailnetwork

  MyRetailCassandra:
    container_name: MyRetailCassandra
    image: cassandra:latest
    volumes:
      - '/My Computer/Java/DB/MyRetail_CASSANDRA:/var/lib/cassandra'
    ports:
      - 9052:9042
    networks:
      - myretailnetwork
      
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - MyRetailCassandra
    volumes:
      - $PWD/scripts/schema.cql:/schema.cql 
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh MyRetailCassandra -f /schema.cql"

networks:
    myretailnetwork:
        driver: bridge