version: '3'
services:
  myretailapp:
    image: myretailapp
    build: .
    deploy:
        replicas: 5
    ports:
      - 8080:8080
    networks:
      - myretailnetwork

networks:
    myretailnetwork:
        driver: bridge