apiVersion: apps/v1
kind: Deployment
metadata:
  name: myretail-deployment
  namespace: my-retail-stage
  labels:
    app: myretailapp
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: myretailapp
  template:
    metadata:
      name: myretailapp
      labels:
        app: myretailapp
    spec:
      containers:
        - name: myretailapp
          image: myretailapp:latest
          env:
            - name: APP_ARGS
              value: '-jar /myRetail.jar' # --cassandraHostIP=10.100.208.32 / -DcassandraHostIP=10.100.208.32
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myretail-service
  namespace: my-retail-stage
  labels:
    app: myretailapp
spec:
  selector:
    app: myretailapp
  type: NodePort    #LoadBalancer, ClusterIP
  ports:
    - port: 8080
